version: '3.8'

services:
  app:
    container_name: upload_Sara
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - uploads_volume:/app/uploads
      - recycle_volume:/app/recycle
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

volumes:
  uploads_volume:
  recycle_volume: