version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/movie_db
      - MOVIE_API_URL=https://api.themoviedb.org/3/movie/popular
      - MOVIEDATA_API_URL=https://api.themoviedb.org/3/movie
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=your_jwt_secret_here
      - API_KEY=54b266be4924e4b41e3aa01608db83c6
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:3000/api
      - VITE_BASE_IMAGE_URL=https://image.tmdb.org/t/p
    depends_on:
      - backend
    networks:
      - app-network
  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 40s
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/movie_db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
